appname = polux_mid
httpport = ${POLUX_MID__HTTP_PORT}
runmode = ${POLUX_MID__RUNMODE|prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
Urlruler = ${POLUX_MID__RULER_URL}
Portruler = ${POLUX_MID__RULER_PORT}
Nsruler = ${POLUX_MID__RULER_NS}
PoluxCrudUrl =  ${POLUX_MID__POLUX_CRUD_URL}
PoluxCrudNs =  ${POLUX_MID__POLUX_CRUD_NS}
UrlCrudParametros = ${POLUX_MID__PARAMETROS_URL}
UrlDocumentos = ${POLUX_MID__DOCUMENTOS_URL}
EscanearArchivo = ${ESCANEAR_ARCHIVO}
